### ISSUE TITLE
An option to change the width of modernx

### ISSUE THREAD

**Issue by micro-aries** [cyl0/MordenX#13]
first of all thank you for your script, i was just wondering if there's an option to change the width of the whole osc bar, something like [https://iina.io/images/sc-sky.png](https://iina.io/images/sc-sky.png) or the one on stock osc of mpv  `layout=slimbox`

**Comment by cyl0** [comment]
No, there isn't such an option available. Doing so would require the OSC layout to be re-done entirely, and isn't really within the scope of this script unfortunately.
