### ISSUE TITLE
[Feature Request] MPV Thumbnail script functionality

### ISSUE THREAD

**Issue by lenicyl** [cyl0/MordenX#16]
[MPV thumbnail script](https://github.com/marzzzello/mpv_thumbnail_script) basically shows preview thumbnails when hovering over mpv's seekbar.

It does not work with MordenX and appears broken, which is believe is due to the fact that it replaces the built-in OSC, which conflicts with MordenX.

I just wanted to know if it was possible to somehow use this script with mordenX, or maybe add its functionality ?

Thank you !

**Comment by couleurm** [comment]
MordenX for the looks, mpv-thumbnail-script for the convenience, would be great to have both 👍

**Comment by lostb053** [comment]
Precisely, I'd love to see that too.

**Comment by winclyde** [comment]
I've made a quick and dirty thumbnailer implementation here: https://github.com/winclyde/MordenX/commit/5cb7fa6cb0b42f8e5618994010489cc4ef731ea8
It's based a downstream thumbnailer implementation from https://github.com/dexeonify/mpv-config/commit/2b6e2b268cfa39f008ee1011636121f3714ddb41, and seems to work great with the Thumbnailer.lua and Thumbnailer_Worker.lua files from https://github.com/deus0ww/mpv-conf/tree/master/scripts.

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/20222974/184531591-b136e994-a6e2-48a7-805d-fc9f84cdc4f1.png">


Perhaps we could get a branch going and get it implemented properly here?

**Comment by dexeonify** [comment]
The same method can be applied to [mpv_thumbnail_script](https://github.com/marzzzello/mpv_thumbnail_script) btw. Diffing the Thumbnailer’s OSC and mpv’s osc.lua, then apply the diffs to MordenX’s OSC.

**Comment by NaiveInvestigator** [comment]
Or we could also try out integrating this script too.
https://github.com/po5/thumbfast

**Comment by cyl0** [comment]
This would be a nice feature to have, I've created a branch.

**Comment by winkyc** [comment]
The [thumbnailer-dev](https://github.com/cyl0/MordenX/tree/thumbnailer-dev) branch should now have a [thumbfast](https://github.com/po5/thumbfast) implementation.

**Comment by winkyc** [comment]
It currently doesn't scale with the rest of the UI at all since its size is determined by thumbfast. I'll have to look into it further to see if we can get the thumbnail to scale properly.
