### ISSUE TITLE
buttons not rendering on click while the video is paused

### ISSUE THREAD

**Issue by computator1200** [cyl0/MordenX#8]
while the video is paused, the window control buttons (from the osc) and the play button won't show that same darkening effect when you click them. It only works while the video isn't paused, is there any way to fix this? @cyl0 

I'm using windows 10.0.19043.1526

**Comment by computator1200** [comment]
> What exactly do you mean by the darkening effect? If by "darkening effect" you mean the greying out of the icon on click like in this screenshot, then I can't seem to replicate your issue. <img alt="Untitled" width="346" src="https://user-images.githubusercontent.com/83499175/155873518-3e7669cc-67c2-4a57-a74a-10cc012b1110.png">
> 
> What build of MPV are you using?

yes that, it doesn't become grey, I'm using mpv 0.34.0-198-gbc9805c71a

**Comment by computator1200** [comment]
ok it's working now, turns out I changed the seekbarfg color to green and that messed it up. Btw is there a way to change the color without this happening

**Comment by cyl0** [comment]
Well that's strange, I'll have to look into this further.

**Comment by computator1200** [comment]
> ok it's working now, turns out I changed the seekbarfg color to green and that messed it up.
> 
> I had changed the line `SeekbarFg = '{\\blur1\\bord1\\1c&H58C41C&}',` with `SeekbarFg = '{\\blur1\\bord1\\1c&HE39C42&}',`
> 
> Btw is there a way to change the color without this problem happening. How exactly did you set the color for the seekbar.

nevermind it wasn't working, even with the script installed fresh along with the font, the same issue appears.

**Comment by dexeonify** [comment]
These two commits from upstream osc.lua seems to fix it for me locally.
mpv-player/mpv@48f3a26
mpv-player/mpv@89efe82

**Comment by cyl0** [comment]
@computator1200 I've merged the upstream osc.lua patches, could you check if the issue still persists?

**Comment by computator1200** [comment]
> @computator1200 I've merged the upstream osc.lua patches, could you check if the issue still persists?

I've tried the updated mordenx.lua script and it works now, thanks
